title: Pritesh Verma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I am Pritesh also known as love, I am Passionate about learnings new things currently I'm working as a Research Fellow at IIT dharwad.
  <br><br>
  These days I'm working on Eigendecomposition problem and Learning the ML/DL.
  <br><br>
  <a href="https://www.linkedin.com/in/priteshvermaa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
